language: php

sudo: false

git:
  depth: 1

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: hhvm
        - php: nightly
    fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

script:
  - travis_retry ./vendor/bin/phpunit
